#!/usr/bin/env python3
"""Generate a multi-shot hero film and a scroll-scrub frame sequence.

Each shot is generated by Wan2.2. The final frame of each shot is extracted and reused
as the image input for the next shot, creating a temporal chain instead of a slideshow.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import shutil
import subprocess
import sys


def run(cmd: list[str], *, cwd: Path | None = None) -> None:
    print("+", subprocess.list2cmdline(cmd))
    subprocess.run(cmd, cwd=cwd, check=True)


def ffmpeg_exists() -> bool:
    return shutil.which("ffmpeg") is not None


def extract_last_frame(video: Path, image: Path) -> None:
    image.parent.mkdir(parents=True, exist_ok=True)
    run([
        "ffmpeg", "-y", "-sseof", "-0.08", "-i", str(video),
        "-frames:v", "1", "-q:v", "2", str(image)
    ])


def concat_videos(videos: list[Path], output: Path) -> None:
    concat_file = output.parent / "concat.txt"
    concat_file.write_text("\n".join(f"file '{v.resolve()}'" for v in videos) + "\n")
    run([
        "ffmpeg", "-y", "-f", "concat", "-safe", "0", "-i", str(concat_file),
        "-c:v", "libx264", "-preset", "slow", "-crf", "17", "-pix_fmt", "yuv420p",
        "-movflags", "+faststart", str(output)
    ])


def export_scroll_frames(video: Path, out_dir: Path, fps: int) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    run([
        "ffmpeg", "-y", "-i", str(video), "-vf", f"fps={fps}",
        "-c:v", "libwebp", "-quality", "84", "-compression_level", "6",
        str(out_dir / "frame_%04d.webp")
    ])


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--preset", type=Path, required=True)
    parser.add_argument("--wan-dir", type=Path, required=True)
    parser.add_argument("--model-dir", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    args = parser.parse_args()

    if not ffmpeg_exists():
        raise SystemExit("ffmpeg is required")
    if not args.preset.exists():
        raise SystemExit(f"Preset not found: {args.preset}")

    preset = json.loads(args.preset.read_text())
    initial_image = Path(preset["initial_image"])
    if not initial_image.exists():
        raise SystemExit(
            f"Initial image not found: {initial_image}. Update initial_image in {args.preset}."
        )

    output_dir = args.output_dir
    clips_dir = output_dir / "clips"
    refs_dir = output_dir / "refs"
    clips_dir.mkdir(parents=True, exist_ok=True)
    refs_dir.mkdir(parents=True, exist_ok=True)

    current_image = initial_image
    generated: list[Path] = []
    wrapper = Path(__file__).with_name("wan22_clip.py")

    for i, shot in enumerate(preset["shots"], start=1):
        clip = clips_dir / f"{i:02d}_{shot['id']}.mp4"
        cmd = [
            sys.executable, str(wrapper),
            "--wan-dir", str(args.wan_dir),
            "--model-dir", str(args.model_dir),
            "--image", str(current_image),
            "--prompt", shot["prompt"],
            "--output", str(clip),
            "--frames", str(shot.get("frames", 121)),
            "--seed", str(shot.get("seed", preset.get("seed", 42) + i)),
            "--size", shot.get("size", preset.get("size", "1280*704")),
            "--task", shot.get("task", preset.get("task", "ti2v-5B")),
        ]
        run(cmd)
        generated.append(clip)

        # This is the key continuity mechanism: next shot begins from a real generated frame.
        last_frame = refs_dir / f"{i:02d}_{shot['id']}_last.png"
        extract_last_frame(clip, last_frame)
        current_image = last_frame

    master = output_dir / preset.get("master_name", "hero-master.mp4")
    concat_videos(generated, master)
    scroll_fps = int(preset.get("scroll_fps", 12))
    export_scroll_frames(master, output_dir / "scroll_frames", scroll_fps)

    manifest = {
        "master": str(master),
        "scroll_frames": str(output_dir / "scroll_frames"),
        "scroll_fps": scroll_fps,
        "shots": [str(p) for p in generated],
    }
    (output_dir / "manifest.json").write_text(json.dumps(manifest, indent=2))
    print(json.dumps(manifest, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
